[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
anchor_htlc = "GFCAj5pEiuY3JZtYEaBS1Y7v4hr2RiAjLtfmr1C6PJox"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
